<?php

  
/**
 * Implements hook_block_info().
 */
function ajax_feed_block_block_info() {
  $blocks = array();
  $blocks['ajax_feed_block'] = array(
    'info' => t('Ajax Feed Block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ajax_feed_block_block_view($delta='') {
  $block = array();

  switch($delta) {
    case 'ajax_feed_block' :
      //$block['content'] = _blog_feed_block_view();
      break;
  }

  return $block;
}